"""add sent_to_chef_by_id to intervention

Revision ID: 03fb7e7858a3
Revises: 0bae059a5676
Create Date: 2025-12-24 18:04:57.403951

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '03fb7e7858a3'
down_revision: Union[str, Sequence[str], None] = '0bae059a5676'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interventions', sa.Column('sent_to_chef_by_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('interventions', 'sent_to_chef_by_id')
    # ### end Alembic commands ###
