"""Création table report

Revision ID: 62936cc3befc
Revises: bd9919bb32df
Create Date: 2026-05-20 06:19:23.726528

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '62936cc3befc'
down_revision: Union[str, Sequence[str], None] = 'bd9919bb32df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('REFUSAL', 'PROBLEM', 'CLOSURE', name='reporttype'), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('intervention_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['intervention_id'], ['interventions.id'], name='fk_reports_interventions_id'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_reports_user_id'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reports_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reports_id'))

    op.drop_table('reports')
    # ### end Alembic commands ###
