"""add sent_to_worker_by_id to interventions

Revision ID: 7122226b3566
Revises: 03fb7e7858a3
Create Date: 2025-12-25 09:34:01.001944

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7122226b3566'
down_revision: Union[str, Sequence[str], None] = '03fb7e7858a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interventions', sa.Column('sent_to_worker_by_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('interventions', 'sent_to_worker_by_id')
    # ### end Alembic commands ###
