"""inscription utilisateur

Revision ID: 92356e1aa9ce
Revises: c284b2b76f9b
Create Date: 2026-05-10 15:43:45.192393

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '92356e1aa9ce'
down_revision: Union[str, Sequence[str], None] = 'c284b2b76f9b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('interventions', schema=None) as batch_op:
        batch_op.alter_column('processing_by',
               existing_type=sa.DATETIME(),
               type_=sa.Integer(),
               existing_nullable=True)
        batch_op.alter_column('closed_by',
               existing_type=sa.DATETIME(),
               type_=sa.Integer(),
               existing_nullable=True)
        batch_op.alter_column('rejected_by',
               existing_type=sa.DATETIME(),
               type_=sa.Integer(),
               existing_nullable=True)
        batch_op.create_foreign_key('fk_interventions_rejected_by', 'users', ['rejected_by'], ['id'])
        batch_op.create_foreign_key('fk_interventions_processing_by', 'users', ['processing_by'], ['id'])
        batch_op.create_foreign_key('fk_interventions_closed_by', 'users', ['closed_by'], ['id'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('full_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.alter_column('full_name',
               existing_type=sa.VARCHAR(),
               nullable=True)

    with op.batch_alter_table('interventions', schema=None) as batch_op:
        batch_op.drop_constraint('fk_interventions_closed_by', type_='foreignkey')
        batch_op.drop_constraint('fk_interventions_processing_by', type_='foreignkey')
        batch_op.drop_constraint('fk_interventions_rejected_by', type_='foreignkey')
        batch_op.alter_column('rejected_by',
               existing_type=sa.Integer(),
               type_=sa.DATETIME(),
               existing_nullable=True)
        batch_op.alter_column('closed_by',
               existing_type=sa.Integer(),
               type_=sa.DATETIME(),
               existing_nullable=True)
        batch_op.alter_column('processing_by',
               existing_type=sa.Integer(),
               type_=sa.DATETIME(),
               existing_nullable=True)

    # ### end Alembic commands ###
