"""add_status_timestamps_to_interventions

Revision ID: acfd8ce9fe5a
Revises: c284b2b76f9b
Create Date: 2026-04-14 06:48:49.660136

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'acfd8ce9fe5a'
down_revision: Union[str, Sequence[str], None] = 'c284b2b76f9b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('interventions', 'processing_by',
               existing_type=sa.DATETIME(),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('interventions', 'closed_by',
               existing_type=sa.DATETIME(),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('interventions', 'rejected_by',
               existing_type=sa.DATETIME(),
               type_=sa.Integer(),
               existing_nullable=True)
    op.create_foreign_key(None, 'interventions', 'users', ['rejected_by'], ['id'])
    op.create_foreign_key(None, 'interventions', 'users', ['processing_by'], ['id'])
    op.create_foreign_key(None, 'interventions', 'users', ['closed_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'interventions', type_='foreignkey')
    op.drop_constraint(None, 'interventions', type_='foreignkey')
    op.drop_constraint(None, 'interventions', type_='foreignkey')
    op.alter_column('interventions', 'rejected_by',
               existing_type=sa.Integer(),
               type_=sa.DATETIME(),
               existing_nullable=True)
    op.alter_column('interventions', 'closed_by',
               existing_type=sa.Integer(),
               type_=sa.DATETIME(),
               existing_nullable=True)
    op.alter_column('interventions', 'processing_by',
               existing_type=sa.Integer(),
               type_=sa.DATETIME(),
               existing_nullable=True)
    # ### end Alembic commands ###
