"""add roles table and role_id to users

Revision ID: c26ab0e1e793
Revises: 50f9a4de5cc5
Create Date: 2026-01-17 17:44:57.495337

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c26ab0e1e793'
down_revision: Union[str, Sequence[str], None] = '50f9a4de5cc5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_roles_id'), 'roles', ['id'], unique=False)
    # 1) Add role_id column first (SQLite requires batch mode)
    with op.batch_alter_table("users") as batch_op:
        batch_op.add_column(sa.Column("role_id", sa.Integer(), nullable=True))

    # Seed base roles
    op.execute("INSERT INTO roles (id, name, label) VALUES (1, 'ADMIN', 'Administrateur')")
    op.execute("INSERT INTO roles (id, name, label) VALUES (2, 'PREFET', 'Préfet')")
    op.execute("INSERT INTO roles (id, name, label) VALUES (3, 'CHEF_OUVRIER', 'Chef ouvrier')")
    op.execute("INSERT INTO roles (id, name, label) VALUES (4, 'OUVRIER', 'Ouvrier')")

    # Map existing users.role (text) -> users.role_id before dropping the old column
    op.execute("UPDATE users SET role_id = 2 WHERE role = 'PREFET'")
    op.execute("UPDATE users SET role_id = 3 WHERE role = 'CHEF_OUVRIER'")
    op.execute("UPDATE users SET role_id = 4 WHERE role = 'OUVRIER'")
    op.execute("UPDATE users SET role_id = 1 WHERE role = 'ADMIN'")

    # Fallback: any remaining NULL becomes ADMIN
    op.execute("UPDATE users SET role_id = 1 WHERE role_id IS NULL")

    # 2) Add FK + drop old role column (SQLite requires batch mode)
    with op.batch_alter_table("users") as batch_op:
        batch_op.create_foreign_key(
            "fk_users_role_id_roles",
            "roles",
            ["role_id"],
            ["id"],
        )
        batch_op.drop_column("role")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users") as batch_op:
        batch_op.add_column(sa.Column('role', sa.VARCHAR(), nullable=True))
        batch_op.drop_constraint("fk_users_role_id_roles", type_='foreignkey')
        batch_op.drop_column('role_id')

    op.drop_index(op.f('ix_roles_id'), table_name='roles')
    op.drop_table('roles')
    # ### end Alembic commands ###
